#!/bin/sh

# Blacklist
# .blacklist [
  # "screen sharing"
# ]

# Navigation
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Moving windows
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# Move focus container to workspace
#shift + alt - 1 : yabai -m window --space 1
#shift + alt - 2 : yabai -m window --space 2
#shift + alt - 3 : yabai -m window --space 3
#shift + alt - 4 : yabai -m window --space 4
#shift + alt - 5 : yabai -m window --space 5

# Resize windows
ctrl + alt - h : \
    yabai -m window --resize left:-100:0 ; \
    yabai -m window --resize right:-100:0

ctrl + alt - j : \
    yabai -m window --resize bottom:0:100 ; \
    yabai -m window --resize top:0:100

ctrl + alt - k : \
    yabai -m window --resize top:0:-100 ; \
    yabai -m window --resize bottom:0:-100

ctrl + alt - l : \
    yabai -m window --resize right:100:0 ; \
    yabai -m window --resize left:100:0

# Float and center window
shift + alt - c : yabai -m window --toggle float;\
                yabai -m window --grid 4:4:1:1:2:2

# Set insertion point for focused container
shift + ctrl + alt - h : yabai -m window --insert west
shift + ctrl + alt - j : yabai -m window --insert south
shift + ctrl + alt - k : yabai -m window --insert north
shift + ctrl + alt - l : yabai -m window --insert east

# Float / Unfloat window
shift + alt - space : yabai -m window --toggle float

# Make fullscreen
alt - f : yabai -m window --toggle zoom-fullscreen

#rotate
alt - r : yabai -m space --rotate 90

# Mirror Space on X and Y Axis: shift + lalt + {x, y}
ctrl + alt - x : yabai -m space --mirror x-axis
ctrl + alt - y : yabai -m space --mirror y-axis

# Stack Navigation: ctrl + {n, p}
shift + ctrl - n : yabai -m window --focus stack.next
shift + ctrl - p : yabai -m window --focus stack.prev

# Equalize size of windows: ctrl + lalt + e
ctrl + lalt - e : yabai -m space --balance

# iTerm2
cmd - return : open -a iTerm

# Create a new desktop, send the currently active window to the new desktop, and automatically jump to the new desktop. jq needs to support brew install jq
shift + cmd - n : yabai -m space --create && index="$(yabai -m query --spaces --display | jq '.| length')" && yabai -m window --space "${index}" && yabai -m space --focus "${index}"

# Switch back to the nearest desktop
ctrl + alt - x : yabai -m space --focus recent
# Switch back to the first desktop
ctrl + alt - 1 : yabai -m space --focus 1
ctrl + alt - 2 : yabai -m space --focus 2
ctrl + alt - 3 : yabai -m space --focus 3
ctrl + alt - 4 : yabai -m space --focus 4
ctrl + alt - 5 : yabai -m space --focus 5
ctrl + alt - 6 : yabai -m space --focus 6
ctrl + alt - 7 : yabai -m space --focus 7
ctrl + alt - 8 : yabai -m space --focus 8
ctrl + alt - 9 : yabai -m space --focus 9
# Close the current desktop
cmd + alt - w : yabai -m space --destroy

# send window to desktop and follow focus
shift + ctrl + alt - z : yabai -m window --space next; yabai -m space --focus next
shift + ctrl + alt - 1 : yabai -m window --space  1; yabai -m space --focus 1
shift + ctrl + alt - 2 : yabai -m window --space  2; yabai -m space --focus 2
shift + ctrl + alt - 3 : yabai -m window --space  3; yabai -m space --focus 3
shift + ctrl + alt - 4 : yabai -m window --space  4; yabai -m space --focus 4
shift + ctrl + alt - 5 : yabai -m window --space  5; yabai -m space --focus 5
shift + ctrl + alt - 6 : yabai -m window --space  6; yabai -m space --focus 6
shift + ctrl + alt - 7 : yabai -m window --space  7; yabai -m space --focus 7
shift + ctrl + alt - 8 : yabai -m window --space  8; yabai -m space --focus 8
shift + ctrl + alt - 9 : yabai -m window --space  9; yabai -m space --focus 9
